# Makefile for binplotlib library
# ===============================
# by E.G.Thomas
include $(MAKECFG).$(SYSTEM)

INCLUDE = -I$(IPATH)/base -I$(IPATH)/general

SRC = plot_logo.c text_box.c

OBJS = plot_logo.o text_box.o

INC = $(IPATH)/base
DSTPATH = $(LIBPATH)
OUTPUT = binplot
LINK = "1"

include $(MAKELIB).$(SYSTEM)
